"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .neodeerror import NeodeError
from typing import Any, TYPE_CHECKING

from neode.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .error import Error, ErrorData
    from .insufficientcreditserror import (
        InsufficientCreditsError,
        InsufficientCreditsErrorData,
    )
    from .neodedefaulterror import NeodeDefaultError
    from .no_response_error import NoResponseError
    from .responsevalidationerror import ResponseValidationError

__all__ = [
    "Error",
    "ErrorData",
    "InsufficientCreditsError",
    "InsufficientCreditsErrorData",
    "NeodeDefaultError",
    "NeodeError",
    "NoResponseError",
    "ResponseValidationError",
]

_dynamic_imports: dict[str, str] = {
    "Error": ".error",
    "ErrorData": ".error",
    "InsufficientCreditsError": ".insufficientcreditserror",
    "InsufficientCreditsErrorData": ".insufficientcreditserror",
    "NeodeDefaultError": ".neodedefaulterror",
    "NoResponseError": ".no_response_error",
    "ResponseValidationError": ".responsevalidationerror",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
