"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from neode.errors import NeodeError
from neode.types import BaseModel
from typing import Optional


class ErrorData(BaseModel):
    success: Optional[bool] = None
    error: Optional[str] = None
    details: Optional[str] = None


@dataclass(unsafe_hash=True)
class Error(NeodeError):
    r"""Bad request"""

    data: ErrorData = field(hash=False)

    def __init__(
        self, data: ErrorData, raw_response: httpx.Response, body: Optional[str] = None
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
