"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from neode.errors import NeodeError
from neode.types import BaseModel
from typing import Optional


class InsufficientCreditsErrorData(BaseModel):
    success: Optional[bool] = None
    error: Optional[str] = None
    balance_cents: Optional[int] = None
    required_cents: Optional[int] = None
    buy_credits_url: Optional[str] = None


@dataclass(unsafe_hash=True)
class InsufficientCreditsError(NeodeError):
    r"""Error returned when user has insufficient credits"""

    data: InsufficientCreditsErrorData = field(hash=False)

    def __init__(
        self,
        data: InsufficientCreditsErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
