"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import TYPE_CHECKING
from importlib import import_module
import builtins
import sys

if TYPE_CHECKING:
    from .createentityop import CreateEntityResponse, CreateEntityResponseTypedDict
    from .creategraphop import CreateGraphResponse, CreateGraphResponseTypedDict
    from .createindexop import CreateIndexResponse, CreateIndexResponseTypedDict
    from .createtriplesresponse import (
        CreateTriplesResponse,
        CreateTriplesResponseTypedDict,
    )
    from .deleteentityop import DeleteEntityRequest, DeleteEntityRequestTypedDict
    from .deletegraphop import DeleteGraphRequest, DeleteGraphRequestTypedDict
    from .deletetriplesop import (
        DeleteTriplesRequest,
        DeleteTriplesRequestTypedDict,
        DeleteTriplesResponse,
        DeleteTriplesResponseTypedDict,
    )
    from .entity import Entity, EntityTypedDict
    from .entitycreate import EntityCreate, EntityCreateTypedDict
    from .entityupdate import EntityUpdate, EntityUpdateTypedDict
    from .generaterequest import GenerateRequest, GenerateRequestTypedDict
    from .generatetriplesop import (
        Format,
        GenerateTriplesRequest,
        GenerateTriplesRequestTypedDict,
        GenerateTriplesResponse,
        GenerateTriplesResponseTypedDict,
    )
    from .getentityop import (
        GetEntityRequest,
        GetEntityRequestTypedDict,
        GetEntityResponse,
        GetEntityResponseTypedDict,
    )
    from .getgraphop import (
        GetGraphRequest,
        GetGraphRequestTypedDict,
        GetGraphResponse,
        GetGraphResponseTypedDict,
    )
    from .graph import Graph, GraphMetadata, GraphMetadataTypedDict, GraphTypedDict
    from .graphcreate import (
        GraphCreate,
        GraphCreateMetadata,
        GraphCreateMetadataTypedDict,
        GraphCreateTypedDict,
    )
    from .index import Index, IndexTypedDict
    from .indexcreate import IndexCreate, IndexCreateTypedDict
    from .listentitiesop import (
        ListEntitiesRequest,
        ListEntitiesRequestTypedDict,
        ListEntitiesResponse,
        ListEntitiesResponseBody,
        ListEntitiesResponseBodyTypedDict,
        ListEntitiesResponseTypedDict,
    )
    from .listgraphsop import (
        ListGraphsRequest,
        ListGraphsRequestTypedDict,
        ListGraphsResponse,
        ListGraphsResponseBody,
        ListGraphsResponseBodyTypedDict,
        ListGraphsResponseTypedDict,
    )
    from .listindexesop import (
        ListIndexesRequest,
        ListIndexesRequestTypedDict,
        ListIndexesResponse,
        ListIndexesResponseBody,
        ListIndexesResponseBodyTypedDict,
        ListIndexesResponseTypedDict,
    )
    from .querytriplesop import (
        QueryTriplesRequest,
        QueryTriplesRequestTypedDict,
        QueryTriplesResponse,
        QueryTriplesResponseBody,
        QueryTriplesResponseBodyTypedDict,
        QueryTriplesResponseTypedDict,
    )
    from .searchrequest import SearchRequest, SearchRequestTypedDict, Type
    from .security import Security, SecurityTypedDict
    from .semanticsearchgetop import (
        SemanticSearchGetCount,
        SemanticSearchGetCountTypedDict,
        SemanticSearchGetData,
        SemanticSearchGetDataTypedDict,
        SemanticSearchGetRequest,
        SemanticSearchGetRequestTypedDict,
        SemanticSearchGetResponse,
        SemanticSearchGetResponseBody,
        SemanticSearchGetResponseBodyTypedDict,
        SemanticSearchGetResponseTypedDict,
    )
    from .semanticsearchop import (
        SemanticSearchCount,
        SemanticSearchCountTypedDict,
        SemanticSearchData,
        SemanticSearchDataTypedDict,
        SemanticSearchEntity,
        SemanticSearchEntityTypedDict,
        SemanticSearchGraph,
        SemanticSearchGraphTypedDict,
        SemanticSearchMetadata,
        SemanticSearchMetadataTypedDict,
        SemanticSearchObjectType,
        SemanticSearchResponse,
        SemanticSearchResponseTypedDict,
        SemanticSearchTriple,
        SemanticSearchTripleTypedDict,
    )
    from .successmessage import SuccessMessage, SuccessMessageTypedDict
    from .triple import Triple, TripleObjectType, TripleTypedDict
    from .triplebatchcreate import TripleBatchCreate, TripleBatchCreateTypedDict
    from .triplecreate import (
        TripleCreate,
        TripleCreateObjectType,
        TripleCreateTypedDict,
    )
    from .tripleupdate import TripleUpdate, TripleUpdateTypedDict
    from .updateentityop import (
        UpdateEntityRequest,
        UpdateEntityRequestTypedDict,
        UpdateEntityResponse,
        UpdateEntityResponseTypedDict,
    )
    from .updatetripleop import UpdateTripleResponse, UpdateTripleResponseTypedDict

__all__ = [
    "CreateEntityResponse",
    "CreateEntityResponseTypedDict",
    "CreateGraphResponse",
    "CreateGraphResponseTypedDict",
    "CreateIndexResponse",
    "CreateIndexResponseTypedDict",
    "CreateTriplesResponse",
    "CreateTriplesResponseTypedDict",
    "DeleteEntityRequest",
    "DeleteEntityRequestTypedDict",
    "DeleteGraphRequest",
    "DeleteGraphRequestTypedDict",
    "DeleteTriplesRequest",
    "DeleteTriplesRequestTypedDict",
    "DeleteTriplesResponse",
    "DeleteTriplesResponseTypedDict",
    "Entity",
    "EntityCreate",
    "EntityCreateTypedDict",
    "EntityTypedDict",
    "EntityUpdate",
    "EntityUpdateTypedDict",
    "Format",
    "GenerateRequest",
    "GenerateRequestTypedDict",
    "GenerateTriplesRequest",
    "GenerateTriplesRequestTypedDict",
    "GenerateTriplesResponse",
    "GenerateTriplesResponseTypedDict",
    "GetEntityRequest",
    "GetEntityRequestTypedDict",
    "GetEntityResponse",
    "GetEntityResponseTypedDict",
    "GetGraphRequest",
    "GetGraphRequestTypedDict",
    "GetGraphResponse",
    "GetGraphResponseTypedDict",
    "Graph",
    "GraphCreate",
    "GraphCreateMetadata",
    "GraphCreateMetadataTypedDict",
    "GraphCreateTypedDict",
    "GraphMetadata",
    "GraphMetadataTypedDict",
    "GraphTypedDict",
    "Index",
    "IndexCreate",
    "IndexCreateTypedDict",
    "IndexTypedDict",
    "ListEntitiesRequest",
    "ListEntitiesRequestTypedDict",
    "ListEntitiesResponse",
    "ListEntitiesResponseBody",
    "ListEntitiesResponseBodyTypedDict",
    "ListEntitiesResponseTypedDict",
    "ListGraphsRequest",
    "ListGraphsRequestTypedDict",
    "ListGraphsResponse",
    "ListGraphsResponseBody",
    "ListGraphsResponseBodyTypedDict",
    "ListGraphsResponseTypedDict",
    "ListIndexesRequest",
    "ListIndexesRequestTypedDict",
    "ListIndexesResponse",
    "ListIndexesResponseBody",
    "ListIndexesResponseBodyTypedDict",
    "ListIndexesResponseTypedDict",
    "QueryTriplesRequest",
    "QueryTriplesRequestTypedDict",
    "QueryTriplesResponse",
    "QueryTriplesResponseBody",
    "QueryTriplesResponseBodyTypedDict",
    "QueryTriplesResponseTypedDict",
    "SearchRequest",
    "SearchRequestTypedDict",
    "Security",
    "SecurityTypedDict",
    "SemanticSearchCount",
    "SemanticSearchCountTypedDict",
    "SemanticSearchData",
    "SemanticSearchDataTypedDict",
    "SemanticSearchEntity",
    "SemanticSearchEntityTypedDict",
    "SemanticSearchGetCount",
    "SemanticSearchGetCountTypedDict",
    "SemanticSearchGetData",
    "SemanticSearchGetDataTypedDict",
    "SemanticSearchGetRequest",
    "SemanticSearchGetRequestTypedDict",
    "SemanticSearchGetResponse",
    "SemanticSearchGetResponseBody",
    "SemanticSearchGetResponseBodyTypedDict",
    "SemanticSearchGetResponseTypedDict",
    "SemanticSearchGraph",
    "SemanticSearchGraphTypedDict",
    "SemanticSearchMetadata",
    "SemanticSearchMetadataTypedDict",
    "SemanticSearchObjectType",
    "SemanticSearchResponse",
    "SemanticSearchResponseTypedDict",
    "SemanticSearchTriple",
    "SemanticSearchTripleTypedDict",
    "SuccessMessage",
    "SuccessMessageTypedDict",
    "Triple",
    "TripleBatchCreate",
    "TripleBatchCreateTypedDict",
    "TripleCreate",
    "TripleCreateObjectType",
    "TripleCreateTypedDict",
    "TripleObjectType",
    "TripleTypedDict",
    "TripleUpdate",
    "TripleUpdateTypedDict",
    "Type",
    "UpdateEntityRequest",
    "UpdateEntityRequestTypedDict",
    "UpdateEntityResponse",
    "UpdateEntityResponseTypedDict",
    "UpdateTripleResponse",
    "UpdateTripleResponseTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "CreateEntityResponse": ".createentityop",
    "CreateEntityResponseTypedDict": ".createentityop",
    "CreateGraphResponse": ".creategraphop",
    "CreateGraphResponseTypedDict": ".creategraphop",
    "CreateIndexResponse": ".createindexop",
    "CreateIndexResponseTypedDict": ".createindexop",
    "CreateTriplesResponse": ".createtriplesresponse",
    "CreateTriplesResponseTypedDict": ".createtriplesresponse",
    "DeleteEntityRequest": ".deleteentityop",
    "DeleteEntityRequestTypedDict": ".deleteentityop",
    "DeleteGraphRequest": ".deletegraphop",
    "DeleteGraphRequestTypedDict": ".deletegraphop",
    "DeleteTriplesRequest": ".deletetriplesop",
    "DeleteTriplesRequestTypedDict": ".deletetriplesop",
    "DeleteTriplesResponse": ".deletetriplesop",
    "DeleteTriplesResponseTypedDict": ".deletetriplesop",
    "Entity": ".entity",
    "EntityTypedDict": ".entity",
    "EntityCreate": ".entitycreate",
    "EntityCreateTypedDict": ".entitycreate",
    "EntityUpdate": ".entityupdate",
    "EntityUpdateTypedDict": ".entityupdate",
    "GenerateRequest": ".generaterequest",
    "GenerateRequestTypedDict": ".generaterequest",
    "Format": ".generatetriplesop",
    "GenerateTriplesRequest": ".generatetriplesop",
    "GenerateTriplesRequestTypedDict": ".generatetriplesop",
    "GenerateTriplesResponse": ".generatetriplesop",
    "GenerateTriplesResponseTypedDict": ".generatetriplesop",
    "GetEntityRequest": ".getentityop",
    "GetEntityRequestTypedDict": ".getentityop",
    "GetEntityResponse": ".getentityop",
    "GetEntityResponseTypedDict": ".getentityop",
    "GetGraphRequest": ".getgraphop",
    "GetGraphRequestTypedDict": ".getgraphop",
    "GetGraphResponse": ".getgraphop",
    "GetGraphResponseTypedDict": ".getgraphop",
    "Graph": ".graph",
    "GraphMetadata": ".graph",
    "GraphMetadataTypedDict": ".graph",
    "GraphTypedDict": ".graph",
    "GraphCreate": ".graphcreate",
    "GraphCreateMetadata": ".graphcreate",
    "GraphCreateMetadataTypedDict": ".graphcreate",
    "GraphCreateTypedDict": ".graphcreate",
    "Index": ".index",
    "IndexTypedDict": ".index",
    "IndexCreate": ".indexcreate",
    "IndexCreateTypedDict": ".indexcreate",
    "ListEntitiesRequest": ".listentitiesop",
    "ListEntitiesRequestTypedDict": ".listentitiesop",
    "ListEntitiesResponse": ".listentitiesop",
    "ListEntitiesResponseBody": ".listentitiesop",
    "ListEntitiesResponseBodyTypedDict": ".listentitiesop",
    "ListEntitiesResponseTypedDict": ".listentitiesop",
    "ListGraphsRequest": ".listgraphsop",
    "ListGraphsRequestTypedDict": ".listgraphsop",
    "ListGraphsResponse": ".listgraphsop",
    "ListGraphsResponseBody": ".listgraphsop",
    "ListGraphsResponseBodyTypedDict": ".listgraphsop",
    "ListGraphsResponseTypedDict": ".listgraphsop",
    "ListIndexesRequest": ".listindexesop",
    "ListIndexesRequestTypedDict": ".listindexesop",
    "ListIndexesResponse": ".listindexesop",
    "ListIndexesResponseBody": ".listindexesop",
    "ListIndexesResponseBodyTypedDict": ".listindexesop",
    "ListIndexesResponseTypedDict": ".listindexesop",
    "QueryTriplesRequest": ".querytriplesop",
    "QueryTriplesRequestTypedDict": ".querytriplesop",
    "QueryTriplesResponse": ".querytriplesop",
    "QueryTriplesResponseBody": ".querytriplesop",
    "QueryTriplesResponseBodyTypedDict": ".querytriplesop",
    "QueryTriplesResponseTypedDict": ".querytriplesop",
    "SearchRequest": ".searchrequest",
    "SearchRequestTypedDict": ".searchrequest",
    "Type": ".searchrequest",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "SemanticSearchGetCount": ".semanticsearchgetop",
    "SemanticSearchGetCountTypedDict": ".semanticsearchgetop",
    "SemanticSearchGetData": ".semanticsearchgetop",
    "SemanticSearchGetDataTypedDict": ".semanticsearchgetop",
    "SemanticSearchGetRequest": ".semanticsearchgetop",
    "SemanticSearchGetRequestTypedDict": ".semanticsearchgetop",
    "SemanticSearchGetResponse": ".semanticsearchgetop",
    "SemanticSearchGetResponseBody": ".semanticsearchgetop",
    "SemanticSearchGetResponseBodyTypedDict": ".semanticsearchgetop",
    "SemanticSearchGetResponseTypedDict": ".semanticsearchgetop",
    "SemanticSearchCount": ".semanticsearchop",
    "SemanticSearchCountTypedDict": ".semanticsearchop",
    "SemanticSearchData": ".semanticsearchop",
    "SemanticSearchDataTypedDict": ".semanticsearchop",
    "SemanticSearchEntity": ".semanticsearchop",
    "SemanticSearchEntityTypedDict": ".semanticsearchop",
    "SemanticSearchGraph": ".semanticsearchop",
    "SemanticSearchGraphTypedDict": ".semanticsearchop",
    "SemanticSearchMetadata": ".semanticsearchop",
    "SemanticSearchMetadataTypedDict": ".semanticsearchop",
    "SemanticSearchObjectType": ".semanticsearchop",
    "SemanticSearchResponse": ".semanticsearchop",
    "SemanticSearchResponseTypedDict": ".semanticsearchop",
    "SemanticSearchTriple": ".semanticsearchop",
    "SemanticSearchTripleTypedDict": ".semanticsearchop",
    "SuccessMessage": ".successmessage",
    "SuccessMessageTypedDict": ".successmessage",
    "Triple": ".triple",
    "TripleObjectType": ".triple",
    "TripleTypedDict": ".triple",
    "TripleBatchCreate": ".triplebatchcreate",
    "TripleBatchCreateTypedDict": ".triplebatchcreate",
    "TripleCreate": ".triplecreate",
    "TripleCreateObjectType": ".triplecreate",
    "TripleCreateTypedDict": ".triplecreate",
    "TripleUpdate": ".tripleupdate",
    "TripleUpdateTypedDict": ".tripleupdate",
    "UpdateEntityRequest": ".updateentityop",
    "UpdateEntityRequestTypedDict": ".updateentityop",
    "UpdateEntityResponse": ".updateentityop",
    "UpdateEntityResponseTypedDict": ".updateentityop",
    "UpdateTripleResponse": ".updatetripleop",
    "UpdateTripleResponseTypedDict": ".updatetripleop",
}


def dynamic_import(modname, retries=3):
    for attempt in range(retries):
        try:
            return import_module(modname, __package__)
        except KeyError:
            # Clear any half-initialized module and retry
            sys.modules.pop(modname, None)
            if attempt == retries - 1:
                break
    raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = dynamic_import(module_name)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = builtins.list(_dynamic_imports.keys())
    return builtins.sorted(lazy_attrs)
