"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import TYPE_CHECKING
from importlib import import_module
import builtins
import sys

if TYPE_CHECKING:
    from .createtriplesresponse import (
        CreateTriplesResponse,
        CreateTriplesResponseTypedDict,
    )
    from .deleteentityop import DeleteEntityRequest, DeleteEntityRequestTypedDict
    from .deletegraphop import DeleteGraphRequest, DeleteGraphRequestTypedDict
    from .deletetriplesop import DeleteTriplesRequest, DeleteTriplesRequestTypedDict
    from .deletetriplesresponse import (
        DeleteTriplesResponse,
        DeleteTriplesResponseTypedDict,
    )
    from .entitieslistresponse import (
        EntitiesListResponse,
        EntitiesListResponseTypedDict,
    )
    from .entity import Entity, EntityTypedDict
    from .entitycreate import EntityCreate, EntityCreateTypedDict
    from .entityresponse import EntityResponse, EntityResponseTypedDict
    from .entityupdate import EntityUpdate, EntityUpdateTypedDict
    from .generaterequest import GenerateRequest, GenerateRequestTypedDict
    from .generatetriplesop import (
        Format,
        GenerateTriplesRequest,
        GenerateTriplesRequestTypedDict,
    )
    from .generatetriplesresponse import (
        GenerateTriplesResponse,
        GenerateTriplesResponseTypedDict,
    )
    from .getentityop import GetEntityRequest, GetEntityRequestTypedDict
    from .getgraphop import GetGraphRequest, GetGraphRequestTypedDict
    from .graph import Graph, GraphMetadata, GraphMetadataTypedDict, GraphTypedDict
    from .graphcreate import (
        GraphCreate,
        GraphCreateMetadata,
        GraphCreateMetadataTypedDict,
        GraphCreateTypedDict,
    )
    from .graphresponse import GraphResponse, GraphResponseTypedDict
    from .graphslistresponse import GraphsListResponse, GraphsListResponseTypedDict
    from .index import Index, IndexTypedDict
    from .indexcreate import IndexCreate, IndexCreateTypedDict
    from .indexeslistresponse import IndexesListResponse, IndexesListResponseTypedDict
    from .indexresponse import IndexResponse, IndexResponseTypedDict
    from .listentitiesop import (
        ListEntitiesRequest,
        ListEntitiesRequestTypedDict,
        ListEntitiesResponse,
        ListEntitiesResponseTypedDict,
    )
    from .listgraphsop import (
        ListGraphsRequest,
        ListGraphsRequestTypedDict,
        ListGraphsResponse,
        ListGraphsResponseTypedDict,
    )
    from .listindexesop import (
        ListIndexesRequest,
        ListIndexesRequestTypedDict,
        ListIndexesResponse,
        ListIndexesResponseTypedDict,
    )
    from .querytriplesop import (
        QueryTriplesRequest,
        QueryTriplesRequestTypedDict,
        QueryTriplesResponse,
        QueryTriplesResponseTypedDict,
    )
    from .searchrequest import SearchRequest, SearchRequestTypedDict
    from .searchtype import SearchType
    from .security import Security, SecurityTypedDict
    from .semanticsearchcount import SemanticSearchCount, SemanticSearchCountTypedDict
    from .semanticsearchdata import (
        SemanticSearchData,
        SemanticSearchDataEntity,
        SemanticSearchDataEntityTypedDict,
        SemanticSearchDataGraph,
        SemanticSearchDataGraphTypedDict,
        SemanticSearchDataMetadata,
        SemanticSearchDataMetadataTypedDict,
        SemanticSearchDataObjectType,
        SemanticSearchDataTriple,
        SemanticSearchDataTripleTypedDict,
        SemanticSearchDataTypedDict,
    )
    from .semanticsearchgetop import (
        SemanticSearchGetRequest,
        SemanticSearchGetRequestTypedDict,
        SemanticSearchGetResponse,
        SemanticSearchGetResponseTypedDict,
    )
    from .semanticsearchresponse import (
        SemanticSearchResponse,
        SemanticSearchResponseTypedDict,
    )
    from .successmessage import SuccessMessage, SuccessMessageTypedDict
    from .triple import Triple, TripleObjectType, TripleTypedDict
    from .triplebatchcreate import TripleBatchCreate, TripleBatchCreateTypedDict
    from .triplecreate import (
        TripleCreate,
        TripleCreateObjectType,
        TripleCreateTypedDict,
    )
    from .tripleslistresponse import TriplesListResponse, TriplesListResponseTypedDict
    from .tripleupdate import TripleUpdate, TripleUpdateTypedDict
    from .updateentityop import UpdateEntityRequest, UpdateEntityRequestTypedDict
    from .updatetripleresponse import (
        UpdateTripleResponse,
        UpdateTripleResponseTypedDict,
    )

__all__ = [
    "CreateTriplesResponse",
    "CreateTriplesResponseTypedDict",
    "DeleteEntityRequest",
    "DeleteEntityRequestTypedDict",
    "DeleteGraphRequest",
    "DeleteGraphRequestTypedDict",
    "DeleteTriplesRequest",
    "DeleteTriplesRequestTypedDict",
    "DeleteTriplesResponse",
    "DeleteTriplesResponseTypedDict",
    "EntitiesListResponse",
    "EntitiesListResponseTypedDict",
    "Entity",
    "EntityCreate",
    "EntityCreateTypedDict",
    "EntityResponse",
    "EntityResponseTypedDict",
    "EntityTypedDict",
    "EntityUpdate",
    "EntityUpdateTypedDict",
    "Format",
    "GenerateRequest",
    "GenerateRequestTypedDict",
    "GenerateTriplesRequest",
    "GenerateTriplesRequestTypedDict",
    "GenerateTriplesResponse",
    "GenerateTriplesResponseTypedDict",
    "GetEntityRequest",
    "GetEntityRequestTypedDict",
    "GetGraphRequest",
    "GetGraphRequestTypedDict",
    "Graph",
    "GraphCreate",
    "GraphCreateMetadata",
    "GraphCreateMetadataTypedDict",
    "GraphCreateTypedDict",
    "GraphMetadata",
    "GraphMetadataTypedDict",
    "GraphResponse",
    "GraphResponseTypedDict",
    "GraphTypedDict",
    "GraphsListResponse",
    "GraphsListResponseTypedDict",
    "Index",
    "IndexCreate",
    "IndexCreateTypedDict",
    "IndexResponse",
    "IndexResponseTypedDict",
    "IndexTypedDict",
    "IndexesListResponse",
    "IndexesListResponseTypedDict",
    "ListEntitiesRequest",
    "ListEntitiesRequestTypedDict",
    "ListEntitiesResponse",
    "ListEntitiesResponseTypedDict",
    "ListGraphsRequest",
    "ListGraphsRequestTypedDict",
    "ListGraphsResponse",
    "ListGraphsResponseTypedDict",
    "ListIndexesRequest",
    "ListIndexesRequestTypedDict",
    "ListIndexesResponse",
    "ListIndexesResponseTypedDict",
    "QueryTriplesRequest",
    "QueryTriplesRequestTypedDict",
    "QueryTriplesResponse",
    "QueryTriplesResponseTypedDict",
    "SearchRequest",
    "SearchRequestTypedDict",
    "SearchType",
    "Security",
    "SecurityTypedDict",
    "SemanticSearchCount",
    "SemanticSearchCountTypedDict",
    "SemanticSearchData",
    "SemanticSearchDataEntity",
    "SemanticSearchDataEntityTypedDict",
    "SemanticSearchDataGraph",
    "SemanticSearchDataGraphTypedDict",
    "SemanticSearchDataMetadata",
    "SemanticSearchDataMetadataTypedDict",
    "SemanticSearchDataObjectType",
    "SemanticSearchDataTriple",
    "SemanticSearchDataTripleTypedDict",
    "SemanticSearchDataTypedDict",
    "SemanticSearchGetRequest",
    "SemanticSearchGetRequestTypedDict",
    "SemanticSearchGetResponse",
    "SemanticSearchGetResponseTypedDict",
    "SemanticSearchResponse",
    "SemanticSearchResponseTypedDict",
    "SuccessMessage",
    "SuccessMessageTypedDict",
    "Triple",
    "TripleBatchCreate",
    "TripleBatchCreateTypedDict",
    "TripleCreate",
    "TripleCreateObjectType",
    "TripleCreateTypedDict",
    "TripleObjectType",
    "TripleTypedDict",
    "TripleUpdate",
    "TripleUpdateTypedDict",
    "TriplesListResponse",
    "TriplesListResponseTypedDict",
    "UpdateEntityRequest",
    "UpdateEntityRequestTypedDict",
    "UpdateTripleResponse",
    "UpdateTripleResponseTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "CreateTriplesResponse": ".createtriplesresponse",
    "CreateTriplesResponseTypedDict": ".createtriplesresponse",
    "DeleteEntityRequest": ".deleteentityop",
    "DeleteEntityRequestTypedDict": ".deleteentityop",
    "DeleteGraphRequest": ".deletegraphop",
    "DeleteGraphRequestTypedDict": ".deletegraphop",
    "DeleteTriplesRequest": ".deletetriplesop",
    "DeleteTriplesRequestTypedDict": ".deletetriplesop",
    "DeleteTriplesResponse": ".deletetriplesresponse",
    "DeleteTriplesResponseTypedDict": ".deletetriplesresponse",
    "EntitiesListResponse": ".entitieslistresponse",
    "EntitiesListResponseTypedDict": ".entitieslistresponse",
    "Entity": ".entity",
    "EntityTypedDict": ".entity",
    "EntityCreate": ".entitycreate",
    "EntityCreateTypedDict": ".entitycreate",
    "EntityResponse": ".entityresponse",
    "EntityResponseTypedDict": ".entityresponse",
    "EntityUpdate": ".entityupdate",
    "EntityUpdateTypedDict": ".entityupdate",
    "GenerateRequest": ".generaterequest",
    "GenerateRequestTypedDict": ".generaterequest",
    "Format": ".generatetriplesop",
    "GenerateTriplesRequest": ".generatetriplesop",
    "GenerateTriplesRequestTypedDict": ".generatetriplesop",
    "GenerateTriplesResponse": ".generatetriplesresponse",
    "GenerateTriplesResponseTypedDict": ".generatetriplesresponse",
    "GetEntityRequest": ".getentityop",
    "GetEntityRequestTypedDict": ".getentityop",
    "GetGraphRequest": ".getgraphop",
    "GetGraphRequestTypedDict": ".getgraphop",
    "Graph": ".graph",
    "GraphMetadata": ".graph",
    "GraphMetadataTypedDict": ".graph",
    "GraphTypedDict": ".graph",
    "GraphCreate": ".graphcreate",
    "GraphCreateMetadata": ".graphcreate",
    "GraphCreateMetadataTypedDict": ".graphcreate",
    "GraphCreateTypedDict": ".graphcreate",
    "GraphResponse": ".graphresponse",
    "GraphResponseTypedDict": ".graphresponse",
    "GraphsListResponse": ".graphslistresponse",
    "GraphsListResponseTypedDict": ".graphslistresponse",
    "Index": ".index",
    "IndexTypedDict": ".index",
    "IndexCreate": ".indexcreate",
    "IndexCreateTypedDict": ".indexcreate",
    "IndexesListResponse": ".indexeslistresponse",
    "IndexesListResponseTypedDict": ".indexeslistresponse",
    "IndexResponse": ".indexresponse",
    "IndexResponseTypedDict": ".indexresponse",
    "ListEntitiesRequest": ".listentitiesop",
    "ListEntitiesRequestTypedDict": ".listentitiesop",
    "ListEntitiesResponse": ".listentitiesop",
    "ListEntitiesResponseTypedDict": ".listentitiesop",
    "ListGraphsRequest": ".listgraphsop",
    "ListGraphsRequestTypedDict": ".listgraphsop",
    "ListGraphsResponse": ".listgraphsop",
    "ListGraphsResponseTypedDict": ".listgraphsop",
    "ListIndexesRequest": ".listindexesop",
    "ListIndexesRequestTypedDict": ".listindexesop",
    "ListIndexesResponse": ".listindexesop",
    "ListIndexesResponseTypedDict": ".listindexesop",
    "QueryTriplesRequest": ".querytriplesop",
    "QueryTriplesRequestTypedDict": ".querytriplesop",
    "QueryTriplesResponse": ".querytriplesop",
    "QueryTriplesResponseTypedDict": ".querytriplesop",
    "SearchRequest": ".searchrequest",
    "SearchRequestTypedDict": ".searchrequest",
    "SearchType": ".searchtype",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "SemanticSearchCount": ".semanticsearchcount",
    "SemanticSearchCountTypedDict": ".semanticsearchcount",
    "SemanticSearchData": ".semanticsearchdata",
    "SemanticSearchDataEntity": ".semanticsearchdata",
    "SemanticSearchDataEntityTypedDict": ".semanticsearchdata",
    "SemanticSearchDataGraph": ".semanticsearchdata",
    "SemanticSearchDataGraphTypedDict": ".semanticsearchdata",
    "SemanticSearchDataMetadata": ".semanticsearchdata",
    "SemanticSearchDataMetadataTypedDict": ".semanticsearchdata",
    "SemanticSearchDataObjectType": ".semanticsearchdata",
    "SemanticSearchDataTriple": ".semanticsearchdata",
    "SemanticSearchDataTripleTypedDict": ".semanticsearchdata",
    "SemanticSearchDataTypedDict": ".semanticsearchdata",
    "SemanticSearchGetRequest": ".semanticsearchgetop",
    "SemanticSearchGetRequestTypedDict": ".semanticsearchgetop",
    "SemanticSearchGetResponse": ".semanticsearchgetop",
    "SemanticSearchGetResponseTypedDict": ".semanticsearchgetop",
    "SemanticSearchResponse": ".semanticsearchresponse",
    "SemanticSearchResponseTypedDict": ".semanticsearchresponse",
    "SuccessMessage": ".successmessage",
    "SuccessMessageTypedDict": ".successmessage",
    "Triple": ".triple",
    "TripleObjectType": ".triple",
    "TripleTypedDict": ".triple",
    "TripleBatchCreate": ".triplebatchcreate",
    "TripleBatchCreateTypedDict": ".triplebatchcreate",
    "TripleCreate": ".triplecreate",
    "TripleCreateObjectType": ".triplecreate",
    "TripleCreateTypedDict": ".triplecreate",
    "TriplesListResponse": ".tripleslistresponse",
    "TriplesListResponseTypedDict": ".tripleslistresponse",
    "TripleUpdate": ".tripleupdate",
    "TripleUpdateTypedDict": ".tripleupdate",
    "UpdateEntityRequest": ".updateentityop",
    "UpdateEntityRequestTypedDict": ".updateentityop",
    "UpdateTripleResponse": ".updatetripleresponse",
    "UpdateTripleResponseTypedDict": ".updatetripleresponse",
}


def dynamic_import(modname, retries=3):
    for attempt in range(retries):
        try:
            return import_module(modname, __package__)
        except KeyError:
            # Clear any half-initialized module and retry
            sys.modules.pop(modname, None)
            if attempt == retries - 1:
                break
    raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = dynamic_import(module_name)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = builtins.list(_dynamic_imports.keys())
    return builtins.sorted(lazy_attrs)
