"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .triple import Triple, TripleTypedDict
from .triplebatchcreate import TripleBatchCreate, TripleBatchCreateTypedDict
from .triplecreate import TripleCreate, TripleCreateTypedDict
from neode.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


CreateTriplesRequestTypedDict = TypeAliasType(
    "CreateTriplesRequestTypedDict",
    Union[TripleBatchCreateTypedDict, TripleCreateTypedDict],
)


CreateTriplesRequest = TypeAliasType(
    "CreateTriplesRequest", Union[TripleBatchCreate, TripleCreate]
)


CreateTriplesDataTypedDict = TypeAliasType(
    "CreateTriplesDataTypedDict", Union[TripleTypedDict, List[TripleTypedDict]]
)


CreateTriplesData = TypeAliasType("CreateTriplesData", Union[Triple, List[Triple]])


class CreateTriplesResponseTypedDict(TypedDict):
    r"""Successfully created"""

    success: NotRequired[bool]
    message: NotRequired[str]
    data: NotRequired[CreateTriplesDataTypedDict]
    inserted_count: NotRequired[int]


class CreateTriplesResponse(BaseModel):
    r"""Successfully created"""

    success: Optional[bool] = None

    message: Optional[str] = None

    data: Optional[CreateTriplesData] = None

    inserted_count: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "message", "data", "inserted_count"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
