"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from neode.types import BaseModel, UNSET_SENTINEL
from neode.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DeleteTriplesRequestTypedDict(TypedDict):
    id: NotRequired[str]
    r"""Single triple ID to delete"""
    ids: NotRequired[str]
    r"""Comma-separated list of triple IDs for batch delete"""


class DeleteTriplesRequest(BaseModel):
    id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Single triple ID to delete"""

    ids: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Comma-separated list of triple IDs for batch delete"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "ids"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class DeleteTriplesResponseTypedDict(TypedDict):
    r"""Successfully deleted"""

    success: NotRequired[bool]
    message: NotRequired[str]
    deleted_count: NotRequired[int]


class DeleteTriplesResponse(BaseModel):
    r"""Successfully deleted"""

    success: Optional[bool] = None

    message: Optional[str] = None

    deleted_count: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "message", "deleted_count"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
