"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from neode.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class DeleteTriplesResponseTypedDict(TypedDict):
    r"""Response from deleting triples"""

    success: NotRequired[bool]
    message: NotRequired[str]
    deleted_count: NotRequired[int]


class DeleteTriplesResponse(BaseModel):
    r"""Response from deleting triples"""

    success: Optional[bool] = None

    message: Optional[str] = None

    deleted_count: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "message", "deleted_count"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
