"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from neode.types import BaseModel, UNSET_SENTINEL
from neode.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DeleteIndexRequestTypedDict(TypedDict):
    id: str
    delete_entities: NotRequired[bool]
    r"""Also delete all entities in this index"""


class DeleteIndexRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    delete_entities: Annotated[
        Optional[bool],
        pydantic.Field(alias="deleteEntities"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = False
    r"""Also delete all entities in this index"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["deleteEntities"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
