"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from neode.types import BaseModel, UNSET_SENTINEL
from neode.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DeleteGraphRequestTypedDict(TypedDict):
    id: str
    delete_triples: NotRequired[bool]
    r"""Also delete all triples in this graph"""


class DeleteGraphRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    delete_triples: Annotated[
        Optional[bool],
        pydantic.Field(alias="deleteTriples"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = False
    r"""Also delete all triples in this graph"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["deleteTriples"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class DeleteGraphResponseTypedDict(TypedDict):
    r"""Successfully deleted"""

    success: NotRequired[bool]
    message: NotRequired[str]


class DeleteGraphResponse(BaseModel):
    r"""Successfully deleted"""

    success: Optional[bool] = None

    message: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "message"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
