"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .entity import Entity, EntityTypedDict
from neode.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class EntityResponseTypedDict(TypedDict):
    r"""Response containing a single entity"""

    success: NotRequired[bool]
    data: NotRequired[EntityTypedDict]
    r"""An entity representing a subject or object in the knowledge graph"""


class EntityResponse(BaseModel):
    r"""Response containing a single entity"""

    success: Optional[bool] = None

    data: Optional[Entity] = None
    r"""An entity representing a subject or object in the knowledge graph"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
