"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from neode.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class EntityTypedDict(TypedDict):
    r"""An entity representing a subject or object in the knowledge graph"""

    id: NotRequired[str]
    name: NotRequired[str]
    r"""Canonical name of the entity"""
    description: NotRequired[str]
    avatar_url: NotRequired[str]
    index_id: NotRequired[str]
    index_name: NotRequired[str]
    created_at: NotRequired[datetime]
    updated_at: NotRequired[datetime]


class Entity(BaseModel):
    r"""An entity representing a subject or object in the knowledge graph"""

    id: Optional[str] = None

    name: Optional[str] = None
    r"""Canonical name of the entity"""

    description: Optional[str] = None

    avatar_url: Optional[str] = None

    index_id: Optional[str] = None

    index_name: Optional[str] = None

    created_at: Optional[datetime] = None

    updated_at: Optional[datetime] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "name",
                "description",
                "avatar_url",
                "index_id",
                "index_name",
                "created_at",
                "updated_at",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
