"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from neode.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class EntityUpdateTypedDict(TypedDict):
    name: NotRequired[str]
    description: NotRequired[str]
    avatar_url: NotRequired[str]
    index_id: NotRequired[str]
    parent_entity_id: NotRequired[Nullable[str]]
    r"""Parent entity ID for hierarchical organization"""


class EntityUpdate(BaseModel):
    name: Optional[str] = None

    description: Optional[str] = None

    avatar_url: Optional[str] = None

    index_id: Optional[str] = None

    parent_entity_id: OptionalNullable[str] = UNSET
    r"""Parent entity ID for hierarchical organization"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["name", "description", "avatar_url", "index_id", "parent_entity_id"]
        )
        nullable_fields = set(["parent_entity_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
