"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .triple import Triple, TripleTypedDict
from neode.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class GenerateTriplesResponseTypedDict(TypedDict):
    r"""Response from generating triples with AI"""

    success: NotRequired[bool]
    data: NotRequired[List[TripleTypedDict]]
    count: NotRequired[int]
    graph_id: NotRequired[str]
    r"""Graph ID the triples were stored in (auto-created or provided)"""
    provider: NotRequired[str]
    r"""AI provider used (openai)"""
    credits_used: NotRequired[int]
    r"""Credits deducted for generation"""
    balance_remaining: NotRequired[int]
    r"""Remaining credit balance"""
    auto_topup_triggered: NotRequired[bool]
    r"""Whether auto top-up was triggered after this generation"""


class GenerateTriplesResponse(BaseModel):
    r"""Response from generating triples with AI"""

    success: Optional[bool] = None

    data: Optional[List[Triple]] = None

    count: Optional[int] = None

    graph_id: Optional[str] = None
    r"""Graph ID the triples were stored in (auto-created or provided)"""

    provider: Optional[str] = None
    r"""AI provider used (openai)"""

    credits_used: Optional[int] = None
    r"""Credits deducted for generation"""

    balance_remaining: Optional[int] = None
    r"""Remaining credit balance"""

    auto_topup_triggered: Optional[bool] = None
    r"""Whether auto top-up was triggered after this generation"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "success",
                "data",
                "count",
                "graph_id",
                "provider",
                "credits_used",
                "balance_remaining",
                "auto_topup_triggered",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
