"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .generaterequest import GenerateRequest, GenerateRequestTypedDict
from neode.types import BaseModel, UNSET_SENTINEL
from neode.utils import FieldMetadata, QueryParamMetadata, RequestMetadata
import pydantic
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


Format = Literal[
    "stream",
    "json",
]
r"""Response format. Use 'json' for non-streaming response suitable for tool use."""


class GenerateTriplesRequestTypedDict(TypedDict):
    body: GenerateRequestTypedDict
    format_: NotRequired[Format]
    r"""Response format. Use 'json' for non-streaming response suitable for tool use."""


class GenerateTriplesRequest(BaseModel):
    body: Annotated[
        GenerateRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    format_: Annotated[
        Optional[Format],
        pydantic.Field(alias="format"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = "stream"
    r"""Response format. Use 'json' for non-streaming response suitable for tool use."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["format"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
