"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from neode.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class GenerateRequestTypedDict(TypedDict):
    r"""Request to generate triples using AI (OpenAI)"""

    query: str
    r"""Natural language description of what to extract triples about"""
    index_id: str
    r"""Index for entity disambiguation (required)"""
    graph_id: NotRequired[str]
    r"""Graph to store generated triples in"""
    web_search: NotRequired[bool]
    r"""Enable web search for real-time information"""
    triple_count: NotRequired[int]
    r"""Target number of triples to generate (approximate)"""
    predicates: NotRequired[List[str]]
    r"""Restrict to specific predicate types"""
    subject_entity: NotRequired[str]
    r"""Constrain all generated triples to use this exact subject"""
    rules: NotRequired[str]
    r"""Custom rules or instructions for the AI generation"""
    news_search: NotRequired[bool]
    r"""Enable news-specific search for recent events"""
    create_graph: NotRequired[bool]
    r"""Auto-create a graph for generated triples when no graph_id is provided. When true (default) and no graph_id is given, a new graph is created and all generated triples are associated with it."""


class GenerateRequest(BaseModel):
    r"""Request to generate triples using AI (OpenAI)"""

    query: str
    r"""Natural language description of what to extract triples about"""

    index_id: str
    r"""Index for entity disambiguation (required)"""

    graph_id: Optional[str] = None
    r"""Graph to store generated triples in"""

    web_search: Optional[bool] = True
    r"""Enable web search for real-time information"""

    triple_count: Optional[int] = 10
    r"""Target number of triples to generate (approximate)"""

    predicates: Optional[List[str]] = None
    r"""Restrict to specific predicate types"""

    subject_entity: Optional[str] = None
    r"""Constrain all generated triples to use this exact subject"""

    rules: Optional[str] = None
    r"""Custom rules or instructions for the AI generation"""

    news_search: Optional[bool] = False
    r"""Enable news-specific search for recent events"""

    create_graph: Optional[bool] = True
    r"""Auto-create a graph for generated triples when no graph_id is provided. When true (default) and no graph_id is given, a new graph is created and all generated triples are associated with it."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "graph_id",
                "web_search",
                "triple_count",
                "predicates",
                "subject_entity",
                "rules",
                "news_search",
                "create_graph",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
