"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .graph import Graph, GraphTypedDict
from neode.types import BaseModel, UNSET_SENTINEL
from neode.utils import FieldMetadata, PathParamMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetGraphRequestTypedDict(TypedDict):
    id: str


class GetGraphRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class GetGraphResponseTypedDict(TypedDict):
    r"""Successful response"""

    success: NotRequired[bool]
    data: NotRequired[GraphTypedDict]
    r"""A graph organizing related triples"""


class GetGraphResponse(BaseModel):
    r"""Successful response"""

    success: Optional[bool] = None

    data: Optional[Graph] = None
    r"""A graph organizing related triples"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
