"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .graph import Graph, GraphTypedDict
from neode.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class GraphsListResponseTypedDict(TypedDict):
    r"""Response containing a list of graphs"""

    success: NotRequired[bool]
    data: NotRequired[List[GraphTypedDict]]
    count: NotRequired[int]


class GraphsListResponse(BaseModel):
    r"""Response containing a list of graphs"""

    success: Optional[bool] = None

    data: Optional[List[Graph]] = None

    count: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "data", "count"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
