"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from neode.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class GraphMetadataTypedDict(TypedDict):
    pass


class GraphMetadata(BaseModel):
    pass


class GraphTypedDict(TypedDict):
    r"""A graph organizing related triples"""

    id: NotRequired[str]
    name: NotRequired[str]
    description: NotRequired[str]
    index_id: NotRequired[str]
    metadata: NotRequired[GraphMetadataTypedDict]
    triple_count: NotRequired[int]
    created_at: NotRequired[datetime]
    updated_at: NotRequired[datetime]


class Graph(BaseModel):
    r"""A graph organizing related triples"""

    id: Optional[str] = None

    name: Optional[str] = None

    description: Optional[str] = None

    index_id: Optional[str] = None

    metadata: Optional[GraphMetadata] = None

    triple_count: Optional[int] = None

    created_at: Optional[datetime] = None

    updated_at: Optional[datetime] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "name",
                "description",
                "index_id",
                "metadata",
                "triple_count",
                "created_at",
                "updated_at",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
