"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from neode.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class IndexUpdateTypedDict(TypedDict):
    r"""Fields to update on an index"""

    name: NotRequired[str]
    description: NotRequired[str]
    is_public: NotRequired[bool]
    preferred_predicates: NotRequired[List[str]]
    r"""Preferred predicate types for this index"""
    rules: NotRequired[str]
    r"""Custom rules or instructions for triple generation in this index"""


class IndexUpdate(BaseModel):
    r"""Fields to update on an index"""

    name: Optional[str] = None

    description: Optional[str] = None

    is_public: Optional[bool] = None

    preferred_predicates: Optional[List[str]] = None
    r"""Preferred predicate types for this index"""

    rules: Optional[str] = None
    r"""Custom rules or instructions for triple generation in this index"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["name", "description", "is_public", "preferred_predicates", "rules"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
