"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from neode.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class IndexTypedDict(TypedDict):
    r"""An index for organizing and disambiguating entities"""

    id: NotRequired[str]
    name: NotRequired[str]
    description: NotRequired[str]
    is_public: NotRequired[bool]
    item_count: NotRequired[int]
    r"""Number of entities in this index"""
    created_at: NotRequired[datetime]
    updated_at: NotRequired[datetime]


class Index(BaseModel):
    r"""An index for organizing and disambiguating entities"""

    id: Optional[str] = None

    name: Optional[str] = None

    description: Optional[str] = None

    is_public: Optional[bool] = None

    item_count: Optional[int] = None
    r"""Number of entities in this index"""

    created_at: Optional[datetime] = None

    updated_at: Optional[datetime] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "name",
                "description",
                "is_public",
                "item_count",
                "created_at",
                "updated_at",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
