"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .index import Index, IndexTypedDict
from neode.types import BaseModel, UNSET_SENTINEL
from neode.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ListIndexesRequestTypedDict(TypedDict):
    search: NotRequired[str]
    r"""Search by name or description"""
    limit: NotRequired[int]
    r"""Maximum number of results"""


class ListIndexesRequest(BaseModel):
    search: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Search by name or description"""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 50
    r"""Maximum number of results"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["search", "limit"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListIndexesResponseTypedDict(TypedDict):
    r"""Successful response"""

    success: NotRequired[bool]
    data: NotRequired[List[IndexTypedDict]]
    count: NotRequired[int]


class ListIndexesResponse(BaseModel):
    r"""Successful response"""

    success: Optional[bool] = None

    data: Optional[List[Index]] = None

    count: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "data", "count"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
