"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .indexeslistresponse import IndexesListResponse, IndexesListResponseTypedDict
from neode.types import BaseModel, UNSET_SENTINEL
from neode.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Awaitable, Callable, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class ListIndexesRequestTypedDict(TypedDict):
    search: NotRequired[str]
    r"""Search by name or description"""
    offset: NotRequired[int]
    r"""Number of results to skip for pagination"""
    limit: NotRequired[int]
    r"""Maximum number of results"""


class ListIndexesRequest(BaseModel):
    search: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Search by name or description"""

    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 0
    r"""Number of results to skip for pagination"""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 50
    r"""Maximum number of results"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["search", "offset", "limit"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListIndexesResponseTypedDict(TypedDict):
    result: IndexesListResponseTypedDict


class ListIndexesResponse(BaseModel):
    next: Union[
        Callable[[], Optional[ListIndexesResponse]],
        Callable[[], Awaitable[Optional[ListIndexesResponse]]],
    ]

    result: IndexesListResponse
