"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .triple import Triple, TripleTypedDict
from neode.types import BaseModel, UNSET_SENTINEL
from neode.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Awaitable, Callable, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class QueryTriplesRequestTypedDict(TypedDict):
    search: NotRequired[str]
    r"""Full-text search across subject, predicate, and object"""
    subject: NotRequired[str]
    r"""Filter by exact subject match"""
    graph_id: NotRequired[str]
    r"""Filter by graph ID"""
    subject_entity_id: NotRequired[str]
    r"""Filter by subject entity ID"""
    object_entity_id: NotRequired[str]
    r"""Filter by object entity ID"""
    predicate: NotRequired[str]
    r"""Filter by predicate (can be repeated for multiple predicates)"""
    offset: NotRequired[int]
    r"""Number of results to skip for pagination"""
    limit: NotRequired[int]
    r"""Maximum number of results"""


class QueryTriplesRequest(BaseModel):
    search: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Full-text search across subject, predicate, and object"""

    subject: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by exact subject match"""

    graph_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by graph ID"""

    subject_entity_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by subject entity ID"""

    object_entity_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by object entity ID"""

    predicate: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by predicate (can be repeated for multiple predicates)"""

    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 0
    r"""Number of results to skip for pagination"""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 50
    r"""Maximum number of results"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "search",
                "subject",
                "graph_id",
                "subject_entity_id",
                "object_entity_id",
                "predicate",
                "offset",
                "limit",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class QueryTriplesResponseBodyTypedDict(TypedDict):
    r"""Successful response"""

    success: NotRequired[bool]
    data: NotRequired[List[TripleTypedDict]]
    count: NotRequired[int]


class QueryTriplesResponseBody(BaseModel):
    r"""Successful response"""

    success: Optional[bool] = None

    data: Optional[List[Triple]] = None

    count: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "data", "count"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class QueryTriplesResponseTypedDict(TypedDict):
    result: QueryTriplesResponseBodyTypedDict


class QueryTriplesResponse(BaseModel):
    next: Union[
        Callable[[], Optional[QueryTriplesResponse]],
        Callable[[], Awaitable[Optional[QueryTriplesResponse]]],
    ]

    result: QueryTriplesResponseBody
