"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


SearchType = Literal[
    "entities",
    "triples",
    "graphs",
]
r"""Type of object to search for"""
