"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .searchtype import SearchType
from neode.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class SearchRequestTypedDict(TypedDict):
    r"""Request for semantic search across the knowledge graph"""

    query: str
    r"""Natural language search query"""
    types: NotRequired[List[SearchType]]
    r"""Types of objects to search"""
    index_id: NotRequired[str]
    r"""Filter results to a specific index"""
    limit: NotRequired[int]
    r"""Maximum results per type"""
    threshold: NotRequired[float]
    r"""Minimum similarity score (0-1)"""


class SearchRequest(BaseModel):
    r"""Request for semantic search across the knowledge graph"""

    query: str
    r"""Natural language search query"""

    types: Optional[List[SearchType]] = None
    r"""Types of objects to search"""

    index_id: Optional[str] = None
    r"""Filter results to a specific index"""

    limit: Optional[int] = 20
    r"""Maximum results per type"""

    threshold: Optional[float] = 0.3
    r"""Minimum similarity score (0-1)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["types", "index_id", "limit", "threshold"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
