"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .searchtype import SearchType
from .semanticsearchresponse import (
    SemanticSearchResponse,
    SemanticSearchResponseTypedDict,
)
from neode.types import BaseModel, UNSET_SENTINEL
from neode.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Awaitable, Callable, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class SemanticSearchGetRequestTypedDict(TypedDict):
    q: str
    r"""Natural language search query"""
    types: NotRequired[List[SearchType]]
    r"""Types to search"""
    index_id: NotRequired[str]
    r"""Filter results to a specific index"""
    offset: NotRequired[int]
    r"""Number of results to skip for pagination"""
    limit: NotRequired[int]
    r"""Maximum results per type (default 20, max 100)"""
    threshold: NotRequired[float]
    r"""Minimum similarity score 0-1 (default 0.3)"""


class SemanticSearchGetRequest(BaseModel):
    q: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Natural language search query"""

    types: Annotated[
        Optional[List[SearchType]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Types to search"""

    index_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter results to a specific index"""

    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 0
    r"""Number of results to skip for pagination"""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 20
    r"""Maximum results per type (default 20, max 100)"""

    threshold: Annotated[
        Optional[float],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 0.3
    r"""Minimum similarity score 0-1 (default 0.3)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["types", "index_id", "offset", "limit", "threshold"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SemanticSearchGetResponseTypedDict(TypedDict):
    result: SemanticSearchResponseTypedDict


class SemanticSearchGetResponse(BaseModel):
    next: Union[
        Callable[[], Optional[SemanticSearchGetResponse]],
        Callable[[], Awaitable[Optional[SemanticSearchGetResponse]]],
    ]

    result: SemanticSearchResponse
