"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from neode.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Literal, Optional
from typing_extensions import NotRequired, TypedDict


class SemanticSearchEntityTypedDict(TypedDict):
    r"""An entity representing a subject or object in the knowledge graph"""

    id: NotRequired[str]
    name: NotRequired[str]
    r"""Canonical name of the entity"""
    description: NotRequired[str]
    avatar_url: NotRequired[str]
    index_id: NotRequired[str]
    index_name: NotRequired[str]
    created_at: NotRequired[datetime]
    updated_at: NotRequired[datetime]
    similarity: NotRequired[float]
    r"""Similarity score (0-1)"""
    triple_count: NotRequired[int]
    r"""Number of related triples"""


class SemanticSearchEntity(BaseModel):
    r"""An entity representing a subject or object in the knowledge graph"""

    id: Optional[str] = None

    name: Optional[str] = None
    r"""Canonical name of the entity"""

    description: Optional[str] = None

    avatar_url: Optional[str] = None

    index_id: Optional[str] = None

    index_name: Optional[str] = None

    created_at: Optional[datetime] = None

    updated_at: Optional[datetime] = None

    similarity: Optional[float] = None
    r"""Similarity score (0-1)"""

    triple_count: Optional[int] = None
    r"""Number of related triples"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "name",
                "description",
                "avatar_url",
                "index_id",
                "index_name",
                "created_at",
                "updated_at",
                "similarity",
                "triple_count",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


SemanticSearchObjectType = Literal[
    "literal",
    "entity",
]
r"""'literal' for values (dates, numbers, text), 'entity' for references to other entities"""


class SemanticSearchTripleTypedDict(TypedDict):
    r"""A knowledge triple representing a fact as subject-predicate-object"""

    subject: str
    r"""The subject entity (e.g., 'Elon Musk', 'Tesla')"""
    predicate: str
    r"""The relationship type (e.g., 'founded', 'located_in', 'born_on')"""
    object: str
    r"""The object value or entity (e.g., 'SpaceX', '2003', 'Austin, Texas')"""
    object_type: SemanticSearchObjectType
    r"""'literal' for values (dates, numbers, text), 'entity' for references to other entities"""
    id: NotRequired[str]
    r"""Unique identifier"""
    confidence: NotRequired[float]
    r"""Confidence score (0-1) indicating reliability"""
    source: NotRequired[str]
    r"""Source URL or reference for this fact"""
    graph_id: NotRequired[str]
    r"""Graph this triple belongs to"""
    index_id: NotRequired[str]
    r"""Index for entity disambiguation"""
    subject_entity_id: NotRequired[str]
    r"""Auto-resolved entity ID for subject"""
    object_entity_id: NotRequired[str]
    r"""Auto-resolved entity ID for object (when object_type is 'entity')"""
    created_at: NotRequired[datetime]
    similarity: NotRequired[float]
    r"""Similarity score (0-1)"""


class SemanticSearchTriple(BaseModel):
    r"""A knowledge triple representing a fact as subject-predicate-object"""

    subject: str
    r"""The subject entity (e.g., 'Elon Musk', 'Tesla')"""

    predicate: str
    r"""The relationship type (e.g., 'founded', 'located_in', 'born_on')"""

    object: str
    r"""The object value or entity (e.g., 'SpaceX', '2003', 'Austin, Texas')"""

    object_type: SemanticSearchObjectType
    r"""'literal' for values (dates, numbers, text), 'entity' for references to other entities"""

    id: Optional[str] = None
    r"""Unique identifier"""

    confidence: Optional[float] = None
    r"""Confidence score (0-1) indicating reliability"""

    source: Optional[str] = None
    r"""Source URL or reference for this fact"""

    graph_id: Optional[str] = None
    r"""Graph this triple belongs to"""

    index_id: Optional[str] = None
    r"""Index for entity disambiguation"""

    subject_entity_id: Optional[str] = None
    r"""Auto-resolved entity ID for subject"""

    object_entity_id: Optional[str] = None
    r"""Auto-resolved entity ID for object (when object_type is 'entity')"""

    created_at: Optional[datetime] = None

    similarity: Optional[float] = None
    r"""Similarity score (0-1)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "confidence",
                "source",
                "graph_id",
                "index_id",
                "subject_entity_id",
                "object_entity_id",
                "created_at",
                "similarity",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SemanticSearchMetadataTypedDict(TypedDict):
    pass


class SemanticSearchMetadata(BaseModel):
    pass


class SemanticSearchGraphTypedDict(TypedDict):
    r"""A graph organizing related triples"""

    id: NotRequired[str]
    name: NotRequired[str]
    description: NotRequired[str]
    index_id: NotRequired[str]
    metadata: NotRequired[SemanticSearchMetadataTypedDict]
    triple_count: NotRequired[int]
    created_at: NotRequired[datetime]
    updated_at: NotRequired[datetime]
    similarity: NotRequired[float]
    r"""Similarity score (0-1)"""


class SemanticSearchGraph(BaseModel):
    r"""A graph organizing related triples"""

    id: Optional[str] = None

    name: Optional[str] = None

    description: Optional[str] = None

    index_id: Optional[str] = None

    metadata: Optional[SemanticSearchMetadata] = None

    triple_count: Optional[int] = None

    created_at: Optional[datetime] = None

    updated_at: Optional[datetime] = None

    similarity: Optional[float] = None
    r"""Similarity score (0-1)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "name",
                "description",
                "index_id",
                "metadata",
                "triple_count",
                "created_at",
                "updated_at",
                "similarity",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SemanticSearchDataTypedDict(TypedDict):
    entities: NotRequired[List[SemanticSearchEntityTypedDict]]
    triples: NotRequired[List[SemanticSearchTripleTypedDict]]
    graphs: NotRequired[List[SemanticSearchGraphTypedDict]]


class SemanticSearchData(BaseModel):
    entities: Optional[List[SemanticSearchEntity]] = None

    triples: Optional[List[SemanticSearchTriple]] = None

    graphs: Optional[List[SemanticSearchGraph]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["entities", "triples", "graphs"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SemanticSearchCountTypedDict(TypedDict):
    entities: NotRequired[int]
    triples: NotRequired[int]
    graphs: NotRequired[int]


class SemanticSearchCount(BaseModel):
    entities: Optional[int] = None

    triples: Optional[int] = None

    graphs: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["entities", "triples", "graphs"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SemanticSearchResponseTypedDict(TypedDict):
    r"""Search results"""

    success: NotRequired[bool]
    data: NotRequired[SemanticSearchDataTypedDict]
    count: NotRequired[SemanticSearchCountTypedDict]


class SemanticSearchResponse(BaseModel):
    r"""Search results"""

    success: Optional[bool] = None

    data: Optional[SemanticSearchData] = None

    count: Optional[SemanticSearchCount] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "data", "count"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
