"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .semanticsearchcount import SemanticSearchCount, SemanticSearchCountTypedDict
from .semanticsearchdata import SemanticSearchData, SemanticSearchDataTypedDict
from neode.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class SemanticSearchResponseTypedDict(TypedDict):
    r"""Response from semantic search"""

    success: NotRequired[bool]
    data: NotRequired[SemanticSearchDataTypedDict]
    r"""Search results data containing entities, triples, and graphs"""
    count: NotRequired[SemanticSearchCountTypedDict]
    r"""Count of search results by type"""


class SemanticSearchResponse(BaseModel):
    r"""Response from semantic search"""

    success: Optional[bool] = None

    data: Optional[SemanticSearchData] = None
    r"""Search results data containing entities, triples, and graphs"""

    count: Optional[SemanticSearchCount] = None
    r"""Count of search results by type"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "data", "count"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
