"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from neode.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


TripleObjectType = Literal[
    "literal",
    "entity",
]
r"""'literal' for values (dates, numbers, text), 'entity' for references to other entities"""


class TripleTypedDict(TypedDict):
    r"""A knowledge triple representing a fact as subject-predicate-object"""

    subject: str
    r"""The subject entity (e.g., 'Elon Musk', 'Tesla')"""
    predicate: str
    r"""The relationship type (e.g., 'founded', 'located_in', 'born_on')"""
    object: str
    r"""The object value or entity (e.g., 'SpaceX', '2003', 'Austin, Texas')"""
    object_type: TripleObjectType
    r"""'literal' for values (dates, numbers, text), 'entity' for references to other entities"""
    id: NotRequired[str]
    r"""Unique identifier"""
    confidence: NotRequired[float]
    r"""Confidence score (0-1) indicating reliability"""
    source: NotRequired[str]
    r"""Source URL or reference for this fact"""
    graph_id: NotRequired[str]
    r"""Graph this triple belongs to"""
    index_id: NotRequired[str]
    r"""Index for entity disambiguation"""
    subject_entity_id: NotRequired[str]
    r"""Auto-resolved entity ID for subject"""
    object_entity_id: NotRequired[str]
    r"""Auto-resolved entity ID for object (when object_type is 'entity')"""
    created_at: NotRequired[datetime]


class Triple(BaseModel):
    r"""A knowledge triple representing a fact as subject-predicate-object"""

    subject: str
    r"""The subject entity (e.g., 'Elon Musk', 'Tesla')"""

    predicate: str
    r"""The relationship type (e.g., 'founded', 'located_in', 'born_on')"""

    object: str
    r"""The object value or entity (e.g., 'SpaceX', '2003', 'Austin, Texas')"""

    object_type: TripleObjectType
    r"""'literal' for values (dates, numbers, text), 'entity' for references to other entities"""

    id: Optional[str] = None
    r"""Unique identifier"""

    confidence: Optional[float] = None
    r"""Confidence score (0-1) indicating reliability"""

    source: Optional[str] = None
    r"""Source URL or reference for this fact"""

    graph_id: Optional[str] = None
    r"""Graph this triple belongs to"""

    index_id: Optional[str] = None
    r"""Index for entity disambiguation"""

    subject_entity_id: Optional[str] = None
    r"""Auto-resolved entity ID for subject"""

    object_entity_id: Optional[str] = None
    r"""Auto-resolved entity ID for object (when object_type is 'entity')"""

    created_at: Optional[datetime] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "confidence",
                "source",
                "graph_id",
                "index_id",
                "subject_entity_id",
                "object_entity_id",
                "created_at",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
