"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from neode.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


TripleCreateObjectType = Literal[
    "literal",
    "entity",
]


class TripleCreateTypedDict(TypedDict):
    subject: str
    predicate: str
    object: str
    object_type: NotRequired[TripleCreateObjectType]
    confidence: NotRequired[float]
    source: NotRequired[str]
    graph_id: NotRequired[str]
    index_id: NotRequired[str]


class TripleCreate(BaseModel):
    subject: str

    predicate: str

    object: str

    object_type: Optional[TripleCreateObjectType] = "literal"

    confidence: Optional[float] = None

    source: Optional[str] = None

    graph_id: Optional[str] = None

    index_id: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["object_type", "confidence", "source", "graph_id", "index_id"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
