"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from neode.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TripleUpdateTypedDict(TypedDict):
    id: str
    subject: NotRequired[str]
    predicate: NotRequired[str]
    object: NotRequired[str]
    confidence: NotRequired[float]
    source: NotRequired[str]
    graph_id: NotRequired[str]


class TripleUpdate(BaseModel):
    id: str

    subject: Optional[str] = None

    predicate: Optional[str] = None

    object: Optional[str] = None

    confidence: Optional[float] = None

    source: Optional[str] = None

    graph_id: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["subject", "predicate", "object", "confidence", "source", "graph_id"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
