"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .triplecreate import TripleCreate, TripleCreateTypedDict
from neode.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class TripleBatchCreateTypedDict(TypedDict):
    triples: List[TripleCreateTypedDict]
    index_id: str
    r"""Index for entity disambiguation (required)"""
    graph_id: NotRequired[str]
    r"""Default graph for all triples"""
    source: NotRequired[str]
    r"""Default source for all triples"""


class TripleBatchCreate(BaseModel):
    triples: List[TripleCreate]

    index_id: str
    r"""Index for entity disambiguation (required)"""

    graph_id: Optional[str] = None
    r"""Default graph for all triples"""

    source: Optional[str] = None
    r"""Default source for all triples"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["graph_id", "source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
