"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .indexupdate import IndexUpdate, IndexUpdateTypedDict
from neode.types import BaseModel
from neode.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateIndexRequestTypedDict(TypedDict):
    id: str
    body: IndexUpdateTypedDict


class UpdateIndexRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    body: Annotated[
        IndexUpdate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
