"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .graphupdate import GraphUpdate, GraphUpdateTypedDict
from neode.types import BaseModel
from neode.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateGraphRequestTypedDict(TypedDict):
    id: str
    body: GraphUpdateTypedDict


class UpdateGraphRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    body: Annotated[
        GraphUpdate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
