"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .entityupdate import EntityUpdate, EntityUpdateTypedDict
from neode.types import BaseModel
from neode.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateEntityRequestTypedDict(TypedDict):
    id: str
    body: EntityUpdateTypedDict


class UpdateEntityRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    body: Annotated[
        EntityUpdate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
