"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .triple import Triple, TripleTypedDict
from neode.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class UpdateTripleResponseTypedDict(TypedDict):
    r"""Response from updating a triple"""

    success: NotRequired[bool]
    message: NotRequired[str]
    data: NotRequired[TripleTypedDict]
    r"""A knowledge triple representing a fact as subject-predicate-object"""


class UpdateTripleResponse(BaseModel):
    r"""Response from updating a triple"""

    success: Optional[bool] = None

    message: Optional[str] = None

    data: Optional[Triple] = None
    r"""A knowledge triple representing a fact as subject-predicate-object"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "message", "data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
